require:
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Exclude:
    - "db/migrate/*"
Rails/LexicallyScopedActionFilter:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "config/environments/production.rb"
    - "config/environments/development.rb"
